let a = 10;
let b = true;
let c = "Foo";
let d = null;
let e = undefined;
alert(`Тип переменной a -  ${typeof a} , значение ${a}`);
alert(`Тип переменной  b - ${typeof b} , значение ${b}`);
alert(`Тип переменной c - ${typeof c}, значение ${c}`);
alert(`Тип переменной d - ${typeof d}, значение ${d}`);
alert(`Тип переменной e - ${typeof e}, значение ${e}`);
